name: Build
run-name: Testing build.

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: sample:kspDebugKotlin --stacktrace
