name: Build
run-name: Testing build.

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: build
